Repository arduino/imgtool-packing, pull requests merged in 2022-05, with the labels that each got.

#5 Add GitHub Actions workflow to synchronize with shared repository labels
  .github/workflows/sync-labels.yml
  README.md
Labels: enhancement, topic: infrastructure

#4 Configure Dependabot to check for outdated actions used in workflows
  .github/dependabot.yml
Labels: enhancement, topic: infrastructure

#11 Add notarization step in the CI
  .github/workflows/release.yml
  build.sh
  entitlements.plist
  gon.config.hcl
Labels: topic: infrastructure

#12 Add version to the binary during build
  .github/workflows/release.yml
  patches/0008-Imgtool-Append-arduino-to-version-string.patch
Labels: type: enhancement, topic: infrastructure, topic: code

#13 Add `package_index.template` generation
  .github/workflows/release.yml
  package_index.template
Labels: type: enhancement, topic: infrastructure

#14 Retain newlines in in package index entry generation command
  .github/workflows/release.yml
Labels: type: imperfection, topic: code
